### ISSUE TITLE
Can't find some data that are on the page

### ISSUE THREAD

**Issue by vinyll** [etalab/recherche.etalab.studio#18]
http://recherche.etalab.studio/?q=d%C3%A9c%C3%A8s should display the dataset "Fichier des personnes décédées — Décès"

**Comment by davidbgk** [comment]
Maybe a consequence of https://github.com/etalab/recherche.etalab.studio/pull/8 ?

**Comment by vinyll** [comment]
fixed in https://github.com/etalab/recherche.etalab.studio/commit/76ec817f2854056945155595b35706014c0edd26
