### ISSUE TITLE
Search bar UI on Safari

### ISSUE THREAD

**Issue by abulte** [etalab/recherche.etalab.studio#3]
Safari desktop MacOS:

<img width="1193" alt="Capture d'écran 2019-12-13 06 44 21" src="https://user-images.githubusercontent.com/119625/70772194-142b1100-1d74-11ea-8189-8528cb1f74fd.png">

**Comment by abulte** [comment]
Better on Safari iOS actually.

![IMG_035216F5F746-1](https://user-images.githubusercontent.com/119625/70772355-8bf93b80-1d74-11ea-9621-fdfb810d42c6.jpeg)

**Comment by vinyll** [comment]
Fixed in the widget approach
