### ISSUE TITLE
Query on "association" returns strange results

### ISSUE THREAD

**Issue by abulte** [etalab/recherche.etalab.studio#33]
Cf `associ` vs `association`

https://recherche.etalab.studio/?q=associ

<img width="1161" alt="Capture d'écran 2020-03-05 16 33 29" src="https://user-images.githubusercontent.com/119625/75997065-14fcba80-5eff-11ea-9c6d-24929929a73b.png">

https://recherche.etalab.studio/?q=association

<img width="1205" alt="Capture d'écran 2020-03-05 16 34 03" src="https://user-images.githubusercontent.com/119625/75997190-48d7e000-5eff-11ea-8a8f-bd78a7be02ed.png">

**Comment by vinyll** [comment]
fixed in https://github.com/etalab/recherche.etalab.studio/commit/76ec817f2854056945155595b35706014c0edd26
