### ISSUE TITLE
Pressing enter does not redirect to data.gouv.fr

### ISSUE THREAD

**Issue by vinyll** [etalab/recherche.etalab.studio#36]
When browsing from recherche.etalab.studio (not when using the wiget), pressing the _enter_ key focused on the search field returns a 404.

**Comment by davidbgk** [comment]
`recherche.etalab.studio` does use the widget but locally, I'm not sure if it's critical given that it is more a demo/test env for now 🤔

**Comment by vinyll** [comment]
I guess that's fine as long as we don't test this version with users :+1:
However, who would be this interface for? Is it for the dev team then?

**Comment by davidbgk** [comment]
I'd love to be able to test with users directly on data.gouv /poke https://github.com/etalab/udata-gouvfr/pull/466

If that's not possible, let's keep that issue opened.

**Comment by vinyll** [comment]
now that we're nunning from the data.gouv.fr this issue is less accurate
