### ISSUE TITLE
Search on "personnes" does not yield "personnes décédées"

### ISSUE THREAD

**Issue by abulte** [etalab/recherche.etalab.studio#37]
<img width="760" alt="Capture d'écran 2020-03-20 14 08 54" src="https://user-images.githubusercontent.com/119625/77166448-941ff000-6ab4-11ea-9213-91db27d99b0a.png">

**Comment by abulte** [comment]
`personne` does not either

**Comment by vinyll** [comment]
Fixed in https://github.com/etalab/recherche.etalab.studio/commit/76ec817f2854056945155595b35706014c0edd26
