### ISSUE TITLE
suivre des comportements utilisateurs

### ISSUE THREAD

**Issue by vinyll** [etalab/recherche.etalab.studio#4]
Ces outils pourraient couvrir le besoin :
- "record and replay the web" https://github.com/rrweb-io/rrweb

Ajouter un suivi des événements Matomo au JS (suivre les recherche à la saisie de texte d'un utilisateur).

**Comment by davidbgk** [comment]
Maybe we should close that one since https://github.com/etalab/recherche.etalab.studio/pull/5 is enough for now.
