### ISSUE TITLE
Taille et placement de la croix pour effacer la recherche

### ISSUE THREAD

**Issue by bzg** [etalab/recherche.etalab.studio#43]
La croix me paraît un peu grande et surtout, elle fait perdre de l'espace vertical entre la barre de recherche (étendue) et les résultats.

Une solution serait peut-être de placer cette croix _à l'intérieur_ du champ de recherche, alignée à droite, pour indiquer d'effacer le contenu actuel du champ ?

![recherche-datagouv](https://user-images.githubusercontent.com/63500/80003769-c82a6e80-84c1-11ea-84e8-861e9dec58c4.png)

**Comment by davidbgk** [comment]
Hopefully fixed in https://github.com/etalab/recherche.etalab.studio/commit/c223b0b1cec8c98a47a3508afdca6c3776490312
