### ISSUE TITLE
Les cartes recherchées ne sont pas les bonnes

### ISSUE THREAD

**Issue by vinyll** [etalab/recherche.etalab.studio#45]
…et la recherche ne se met pas à jour.

[Joel partage un bug](https://teamopendata.org/t/experimentation-data-gouv-fr/2293/5) qui montre une recherche ("élection") qui n'affichage pas les cartes concernant les élections et n'adapte pas l'url (`&q=élection` devrait y apparaitre).

Il précise être sur Ubuntu 19.10 avec un FF75

![copie écran](https://teamopendata.org/uploads/default/original/2X/3/332b9814d7e1858c5dac42a4395ca3765c70d578.png)

**Comment by davidbgk** [comment]
Chez moi c'est parce que la ligne `if(!Piwik) return` ne fonctionne pas si on bloque les trackers: `ReferenceError: Piwik is not defined`

**Comment by davidbgk** [comment]
Fixed in https://github.com/etalab/recherche.etalab.studio/commit/28e21e98030d871ce523ebc89504355634ec9a52
